var menu = {
	'burgers': [
		{
			'name': 'House Burger',
			'price': 10,
			'veg': false,
			'vegan': false,
		},
		{
			'name': 'Local, Grass-fed Burger',
			'price': 11,
			'veg': false,
			'vegan': false,
		},
		{
			'name': 'American Kobe-style Burger',
			'price': 14,
			'veg': false,
			'vegan': false,
		},
		{
			'name': 'Veggie Burger',
			'price': 9,
			'veg': true,
			'vegan': true,
		},
		{
			'name': 'Chicken Breast',
			'price': 8,
			'veg': false,
			'vegan': false,
		},
		{
			'name': 'Yellowfin Tuna Burger',
			'price': 12,
			'veg': false,
			'vegan': false,
		},
		{
			'name': 'Lamb Burger',
			'price': 10,
			'veg': false,
			'vegan': false,
		},
		{
			'name': 'Turkey Burger',
			'price': 9,
			'veg': false,
			'vegan': false,
		},
		{
			'name': 'Bison Burger',
			'price': 12,
			'veg': false,
			'vegan': false,
		},
		{
			'name': 'Salmon Burger',
			'price': 12,
			'veg': false,
			'vegan': false,
		},
	],
	'buns': [
		{
			'name': 'Sesame',
			'price': 0,
			'veg': true,
			'vegan': true,
		},
		{
			'name': 'Brioche',
			'price': 0.5,
			'veg': true,
			'vegan': false,
		},
		{
			'name': 'Herb Ciabatta',
			'price': 0.5,
			'veg': true,
			'vegan': true,
		},
		{
			'name': 'Multigrain',
			'price': 0.75,
			'veg': true,
			'vegan': true,
		},
	],
	'toppings': [
		{
			'name': 'American Cheese',
			'price': 0.75,
			'veg': true,
			'vegan': false,
			'type': ['cheese'],
		},
		{
			'name': 'Cheddar',
			'price': 0.75,
			'veg': true,
			'vegan': false,	
			'type': ['cheese'],
		},
		{
			'name': 'Smoked Gouda',
			'price': 0.75,
			'veg': true,
			'vegan': false,
			'type': ['cheese'],
		},
		{
			'name': 'Sharp Provolone',
			'price': 0.75,
			'veg': true,
			'vegan': false,	
			'type': ['cheese'],
		},
		{
			'name': 'Pepper Jack',
			'price': 0.75,
			'veg': true,
			'vegan': false,
			'type': ['cheese'],	
		},
		{
			'name': 'Gruyère',
			'price': 1.5,
			'veg': true,
			'vegan': false,	
			'type': ['cheese'],
		},
		{
			'name': 'Herb Goat Cheese',
			'price': 1.5,
			'veg': true,
			'vegan': false,
			'type': ['cheese'],	
		},
		{
			'name': 'Habanero Cheddar',
			'price': 1.5,
			'veg': true,
			'vegan': false,	
			'type': ['cheese'],
		},
		{
			'name': 'Smoked Mozzerella',
			'price': 1.5,
			'veg': true,
			'vegan': false,	
			'type': ['cheese'],
		},
		{
			'name': 'Whiskey Cheddar',
			'price': 1.5,
			'veg': true,
			'vegan': false,
			'type': ['cheese'],	
		},
		{
			'name': 'Grain Mustard Cheddar',
			'price': 1.5,
			'veg': true,
			'vegan': false,
			'type': ['cheese'],	
		},
		{
			'name': 'Great Blue Hill Cheese',
			'price': 1.5,
			'veg': true,
			'vegan': false,	
			'type': ['cheese'],
		},
		{
			'name': 'Parmesan Crisp',
			'price': 0.75,
			'veg': true,
			'vegan': false,	
			'type': ['cheese'],
		},
		{
			'name': 'Horseradish Mayo',
			'price': 0.5,
			'veg': true,
			'vegan': false,	
			'type': ['mayo', 'sauce'],
		},
		{
			'name': 'Cilantro Mayo',
			'price': 0.5,
			'veg': true,
			'vegan': false,	
			'type': ['mayo', 'sauce'],
		},
		{
			'name': 'Garlic Mayo',
			'price': 0.5,
			'veg': true,
			'vegan': false,
			'type': ['mayo', 'sauce'],	
		},
		{
			'name': 'BBQ Sauce',
			'price': 0.5,
			'veg': true,
			'vegan': true,
			'type': ['bbq', 'sauce'],
		},
		{
			'name': 'Whiskey BBQ Sauce',
			'price': 0.5,
			'veg': false,
			'vegan': false,
			'type': ['bbq', 'sauce'],	
		},
		{
			'name': 'Ranch',
			'price': 0.5,
			'veg': true,
			'vegan': false,
			'type': ['mayo', 'sauce'],	
		},
		{
			'name': 'Sriracha Aoili',
			'price': 0.5,
			'veg': true,
			'vegan': false,
			'type': ['mayo', 'sauce'],	
		},
		{
			'name': 'Truffle Aoili',
			'price': 0.5,
			'veg': true,
			'vegan': false,
			'type': ['mayo', 'sauce'],
		},
		{
			'name': 'Mac Sauce',
			'price': 0.5,
			'veg': true,
			'vegan': null,
			'type': ['sauce'],	
		},
		{
			'name': "Creamy Frank's Red Hot",
			'price': 0.5,
			'veg': true,
			'vegan': false,
			'type': ['sauce'],	
		},
		{
			'name': 'Honey Mustard',
			'price': 0.5,
			'veg': true,
			'vegan': true,
			'type': ['sauce', 'mustard'],	
		},
		{
			'name': 'Blackberry Champagne BBQ Sauce',
			'price': 0.5,
			'veg': true,
			'vegan': true,
			'type': ['bbq', 'sauce'],
		},
		{
			'name': 'Blue Cheese Dressing',
			'price': 0.75,
			'veg': true,
			'vegan': false,
			'type': ['sauce'],
		},
		{
			'name': 'Sweet Chili Ranch',
			'price': 0.5,
			'veg': true,
			'vegan': false,	
			'type': ['mayo', 'sauce'],
		},
		{
			'name': 'Sundried Tomato and Artichoke Spread',
			'price': 1.5,
			'veg': true,
			'vegan': true,
			'type': ['sauce'],
		},
		{
			'name': 'Lettuce',
			'price': 0,
			'veg': true,
			'vegan': true,	
		},
		{
			'name': 'Tomato',
			'price': 0,
			'veg': true,
			'vegan': true,	
		},
		{
			'name': 'Pickles',
			'price': 0,
			'veg': true,
			'vegan': true,
			'type': ['pickle']
		},
		{
			'name': 'Onion',
			'price': 0,
			'veg': true,
			'vegan': true,
			'type': ['onion'],
		},
		{
			'name': 'Sautéed Mushrooms',
			'price': 0.75,
			'veg': true,
			'vegan': true,	
		},
		{
			'name': 'Frizzled Onions',
			'price': 0.75,
			'veg': true,
			'vegan': true,	
		},
		{
			'name': 'Grilled Onion',
			'price': 0.75,
			'veg': true,
			'vegan': true,	
			'type': ['onion'],
		},
		{
			'name': 'House Slaw',
			'price': 0.75,
			'veg': true,
			'vegan': true,	
		},
		{
			'name': 'Sliced Jalapeño',
			'price': 0.75,
			'veg': true,
			'vegan': true,	
		},
		{
			'name': 'Mustard Pickles',
			'price': 0.75,
			'veg': true,
			'vegan': true,
			'type': ['pickle'],
		},
		{
			'name': 'Fried Pickles',
			'price': 0.75,
			'veg': true,
			'vegan': true,
			'type': ['pickle'],	
		},
		{
			'name': 'Arugula',
			'price': 0.75,
			'veg': true,
			'vegan': true,	
		},
		{
			'name': 'Potato Chips',
			'price': 0.75,
			'veg': true,
			'vegan': true,	
		},
		{
			'name': 'Avocado',
			'price': 1.5,
			'veg': true,
			'vegan': true,	
		},
		{
			'name': 'Fried Egg',
			'price': 1.5,
			'veg': true,
			'vegan': false,	
		},
		{
			'name': 'Beef Chili',
			'price': 1.5,
			'veg': false,
			'vegan': false,	
		},
		{
			'name': 'Bacon',
			'price': 2,
			'veg': false,
			'vegan': false,	
		},
		{
			'name': 'Fried Proscuitto',
			'price': 2,
			'veg': false,
			'vegan': false,	
		},
		{
			'name': 'Pork Belly',
			'price': 2.5,
			'veg': false,
			'vegan': false,	
		},
		{
			'name': 'Espresso Bacon',
			'price': 2.5,
			'veg': false,
			'vegan': false,	
		},
		{
			'name': 'Andouille Sausage',
			'price': 2.5,
			'veg': false,
			'vegan': false,	
		},
		{
			'name': 'Short Rib',
			'price': 3,
			'veg': false,
			'vegan': false,	
		},
		{
			'name': 'North Country Bacon',
			'price': 3.5,
			'veg': false,
			'vegan': false,	
		},
		{
			'name': 'Fried Shrimp',
			'price': 4,
			'veg': false,
			'vegan': false,	
		},
		{
			'name': 'Hash Brown',
			'price': 1,
			'veg': true,
			'vegan': true
		}
	],
};
